import random
import turtle

window = turtle.Screen()
window.setup(width=600, height=480)
window.bgcolor('white')
t = turtle.Turtle()
t.pencolor('blue')
t.begin_fill()
t.fillcolor('lime')
t.forward(100)
t.right(90)
t.forward(100)
t.right(90)
t.forward(100)
t.right(90)
t.forward(100)
t.end_fill()
t.penup()
t.pensize(2)
t.pencolor('black')
t.forward(100)
t.pendown()
t.forward(100)
t.right(90)
t.forward(50)
t.right(90)
t.forward(100)
t.right(90)
t.forward(50)
t.penup()
t.pencolor('red')
t.forward(100)
t.pendown()
t.forward(100)
t.right(90)
t.forward(50)
t.right(90)
t.forward(100)
t.right(90)
t.forward(50)

t.begin_fill()
t.pencolor('green')
t.fillcolor('lime')
t.penup()
t.forward(100)
t.pendown()

t.forward(100)
t.right(120)
t.forward(100)
t.right(120)
t.forward(100)
t.right(120)
t.end_fill()

t.penup()
t.forward(100)
t.pendown()

t.begin_fill()
r = random.random()
g = random.random()
b = random.random()
t.pencolor(r, g, b)
t.fillcolor('grey')
t.forward(100)
t.right(120)
t.forward(100)
t.right(120)
t.forward(100)
t.right(120)
t.end_fill()

print('Выбирайте что хотите нарисовать:')
print('1 - Круг')
print('2 - Квадрат')
print('3 - треугольник')
choose = window.textinput("Введите число от 1 до 3:", "1,2  или 3")
t.penup()
t.setposition(150, 100)
t.pendown()
r = random.random()
g = random.random()
b = random.random()
t.pencolor(r, g, b)
if choose == '1':
    t.circle(50)
elif choose == '2':
    t.forward(100)
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(100)
    t.right(90)
    t.forward(100)
elif choose == '3':
    t.forward(100)
    t.right(120)
    t.forward(100)
    t.right(120)
    t.forward(100)
    t.right(120)
else:
    print('Выбор неверный')

turtle.done()
